server:
  port: 8080
  servlet:
    context-path: /bootcamp
    

spring:
  datasource:    
    driverClassName: org.postgresql.Driver
    url: postgres://aotskxpuvtodbt:450828aebd8f2e92f38a34862a81ba55d07ae5eddc89c1e73404f63eb369afd1@ec2-54-167-152-185.compute-1.amazonaws.com:5432/d20u11m3ka1agm
    username: aotskxpuvtodbt
    password: 450828aebd8f2e92f38a34862a81ba55d07ae5eddc89c1e73404f63eb369afd1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    genereate-ddl: true
    hibernate:
      ddl-auto: none

app:
  description: Projeto bootcamp Angular+java
